import styles from '@/styles/Empanadas.module.css'
import Head from 'next/head'
import HomeBar from '@/components/home_bar'
import { useEffect, useState } from 'react'
import obtener from './api/firebase/get-data'
import modificarDocumento from './api/firebase/update-data'
import ModalPopUp from '@/components/popup/popup'
import Guardar from '@/components/popup/modalGuardado'
import InactivityAlert2 from '@/components/InactivityEmployee'
import { useRouter } from 'next/router'

export default function Empanada() {
    const [numEmpanadas, setNumEmpanadas] = useState([])
    const [fabricar, setFabricar] = useState(0)
    const [open, setOpen] = useState(false)
    const [gramos, setGramos] = useState()
    const [masaAyer, setMasaAyer] = useState()
    const [empanadasAyer, setEmpanadasAyer] = useState()
    const router = useRouter()
    useEffect(() => {
        if (typeof window !== 'undefined') {
            try {
                if (sessionStorage.getItem("acceso") !== "true") {
                    router.push('/');
                }
            } catch (error) {
                router.push('/');
            }
        }
    }, [router]);

    const fetchData = async () => {
        try {
            const result = await obtener("empanadas");
            setNumEmpanadas(result);
        } catch (error) {
            // Handle the error if needed
            console.error("Error fetching data:", error);
        }
    };

    useEffect(() => {
        fetchData();
    }, []);

    useEffect(() => {
        if (numEmpanadas.length > 0) {
            setGramos(numEmpanadas[0].peso);
            setFabricar(Math.floor(numEmpanadas[0].cantidad))
            setMasaAyer(numEmpanadas[0].masaAyer)
            setEmpanadasAyer(numEmpanadas[0].empanadasAyer)
        }
    }, [numEmpanadas]);

    useEffect(() => {
        if (typeof gramos != "undefined") {
            if (gramos >= 45) {
                const cantidad = Math.floor(gramos / 45);
                setFabricar(cantidad)
            }
            else {
                setFabricar(0)
            }
        }
    }, [gramos])
    return (
        <>
            <Head>
                <title>Comedor App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <HomeBar enlace="/inicio"></HomeBar>
                <ModalPopUp
                    openPopUp={open}
                    setOpenPopUp={setOpen}
                >
                    <Guardar></Guardar>
                </ModalPopUp>
                <InactivityAlert2 />
                <div className={styles.inicio}>
                    <div className={styles.block}>
                        <div>
                            <div>
                                <div className={styles.titulos}>Empanadas Para Hoy: <b className={styles.bold}>{fabricar}</b></div>
                            </div>
                        </div>
                        <div>
                            <div>
                                <div className={styles.titulos2}>Empanadas de Ayer: <b className={styles.bold}>{masaAyer}</b></div>
                            </div>
                        </div>
                    </div>
                    <div className={styles.num2}>Total de Empanadas: {fabricar+masaAyer}</div>
                </div>
            </div>
        </>
    )
}