import styles from '@/styles/Inicio.module.css'
import Head from 'next/head'
import HomeBar from '@/components/home_bar'
import Link from 'next/link'
import { useRouter } from "next/router";
import { useEffect } from 'react'

export default function PedidosMenu() {
    const router = useRouter()
    useEffect(() => {
        if (typeof window !== 'undefined') {
            try {
                if (sessionStorage.getItem("acceso") !== "true") {
                    router.push('/');
                }
                if (sessionStorage.getItem("tipo") !== "1") {
                    router.push('/');
                }
            } catch (error) {
                router.push('/');
            }
        }
    }, [router]);
    return (
        <>
            <Head>
                <title>Comedor App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <HomeBar enlace="/menu"></HomeBar>
                <div className={styles.container}>
                    <Link className={styles.panel} href="pedidosRestaurar">
                        <div className={styles.primero}><img src="refresh.png" className={styles.imagen} alt="/imagen no encontrada"></img></div>
                        <div className={styles.segundo}> <div className={styles.sin}>Restaurar Pedidos</div> </div>
                    </Link>
                    <Link className={styles.panel} href="pedidos">
                        <div className={styles.primero}><img src="pedidos.png" className={styles.imagen} alt="/imagen no encontrada"></img></div>
                        <div className={styles.segundo}><div className={styles.sin}>Ver Pedidos</div> </div>
                    </Link>
                </div>
                <div className={styles.container}>
                    <Link className={styles.panel} href="pedidosFinanza">
                        <div className={styles.primero}><img src="busito.png" className={styles.imagen} alt="/imagen no encontrada"></img></div>
                        <div className={styles.segundo}><div className={styles.sin}>Pedidos Enviados</div> </div>
                    </Link>
                    <Link className={styles.panel} href="empanadaAdmin">
                        <div className={styles.primero}><img src="empanada.png" className={styles.imagen} alt="/imagen no encontrada"></img></div>
                        <div className={styles.segundo}><div className={styles.sin}>Admin Empanada</div> </div>
                    </Link>
                </div>
            </div>
        </>
    )
}