import styles from '@/styles/Profile.module.css'
import Head from 'next/head'
import { useEffect, useState } from "react"
import TablaUsuarios from "@/components/tables/tablaUsuarios"
import ModalPopUp from "@/components/popup/popup"
import ModalCrearUser from "@/components/popup/modalCrearUser"
import { useRouter } from "next/router"

const Profile = () => {
    const [nombre, setNombre] = useState("")
    const [openPopUp, setOpenPopUp] = useState(false)
    const [actualizar, setActualizar] = useState(false)
    const [usuariosList, setUsuariosList] = useState([])
    const router = useRouter()

    useEffect(() => {
        if (typeof window !== 'undefined') {
            try {
                if (sessionStorage.getItem("acceso") !== "true") {
                    router.push('/');
                }
                if (sessionStorage.getItem("tipo") !== "1") {
                    router.push('/');
                }else{
                    setNombre(sessionStorage.getItem("usuario"))
                }
            } catch (error) {
                console.error(error)
            }
        }
    }, [])

    return (
        <>
            <Head>
                <title>SupplyPro</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <ModalPopUp
                    openPopUp={openPopUp}
                    setOpenPopUp={setOpenPopUp}
                >
                    <ModalCrearUser  usuariosList={usuariosList} setUsuariosList={setUsuariosList} actualizar={actualizar} setActualizar={setActualizar}></ModalCrearUser>
                </ModalPopUp>
                <div>
                    <div className={styles.centrar}>
                        <div>
                            {
                                // aquí va a ir imagenes cuando pueda poner imagenes
                            }
                        </div>
                        <div>
                            <div>
                                <div className={styles.letras}>Usuario: {nombre}</div>
                            </div>
                        </div>
                    </div>
                    <div className={styles.derecha}>
                        <button className={styles.boton} onClick={()=>setOpenPopUp(true)}>Crear Usuario</button>
                    </div>
                    <div className={styles.tablaUser}>
                        <TablaUsuarios usuariosList={usuariosList} setUsuariosList={setUsuariosList} actualizado={actualizar} setActualizado={setActualizar}></TablaUsuarios>
                    </div>
                </div>
            </div>

        </>
    )
}

export default Profile