import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import HomeBar from "@/components/home_bar";
import { Inter } from 'next/font/google'
import styles from "@/styles/menu.module.css";
import { useRouter } from "next/router";
const InterFont = Inter({ subsets: ['latin'] });
import { useEffect } from 'react'
import InactivityAlert from "@/components/Inactivity";
import MiniDrawer from "../menuV2";

const Home = () => {
  const router = useRouter()
  useEffect(() => {
    if (typeof window !== 'undefined') {
      try {
        if (sessionStorage.getItem("acceso") !== "true") {
          router.push('/');
        }
        if (sessionStorage.getItem("tipo") == "2") {
          router.replace('/mayorista/mayorista-inicio');
        } else if (sessionStorage.getItem("tipo") == "3") {
          router.replace('/minoristas/minorista-inicio');
        } else {
        }
      } catch (error) {
        console.error(error)
      }
    }
  }, [])
  return (
    <div className={InterFont.className}>
      <Head>
        <title>SupplyPro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InactivityAlert />
      <MiniDrawer>
        <div className={styles.menu}>
          <Link href="/financiera">
            <button className={styles.boton}>
              <Image
                src="/../public/dinero.png"
                width={512}
                height={512}
                className={styles.imagen}
                alt="/imagen no encontrada"
              />
              <span className={styles.texto}>Finanzas</span>
            </button>
          </Link>
          <Link href="/fabrica/crearProducto">
            <button className={styles.boton}>
              <Image
                src="/../public/plato.png"
                width={512}
                height={512}
                className={styles.imagen}
                alt="/imagen no encontrada"
              />
              <span className={styles.texto}>Productos</span>
            </button>
          </Link>
          <Link href="/fabrica/inventario">
            <button className={styles.boton}>
              <Image
                src="/../public/caja.png"
                width={512}
                height={512}
                className={styles.imagen}
                alt="/imagen no encontrada"
              />
              <span className={styles.texto}>Inventario</span>
            </button>
          </Link>
        </div>
      </MiniDrawer>
    </div>
  );
}
export default Home