import styles from '@/styles/Inicio.module.css'
import Head from 'next/head'
import HomeBar from '@/components/home_bar'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import InactivityAlert2 from '@/components/InactivityEmployee'
import { useRouter } from 'next/router'

export default function MayoristaInicio() {
    const router = useRouter()
    useEffect(() => {
        if (typeof window !== 'undefined') {
            try {
                if (sessionStorage.getItem("acceso") !== "true") {
                    router.push('/');
                }
            } catch (error) {
                router.push('/');
            }
        }
    }, [router]);
    return (
        <>
            <Head>
                <title>Comedor App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <InactivityAlert2 />
                <HomeBar enlace="/inicio"></HomeBar>
                <div className={styles.container}>
                    <Link className={styles.panel} href="mayorista-fabrica">
                        <div className={styles.primero}><img src="../fabrica.png" className={styles.imagen} alt="/imagen no encontrada"></img></div>
                        <div className={styles.segundo}> <div className={styles.sin}>Fabrica</div> </div>
                    </Link>
                    <Link className={styles.panel} href="mayorista-minorista">
                        <div className={styles.primero}><img src="../minorista.png" className={styles.imagen} alt="/imagen no encontrada"></img></div>
                        <div className={styles.segundo}><div className={styles.sin}>Minoristas</div> </div>
                    </Link>
                </div>
            </div>
        </>
    )
}